# =============================================================================
# fuzzel.ini – App launcher
# Solarized Night palette
# =============================================================================

[main]
font            = JetBrainsMonoNL Nerd Font:size=12
dpi-aware       = auto
prompt          = " "
icon-theme      = Papirus-Dark
icons           = yes
terminal        = kitty
layer           = overlay
exit-on-keyboard-focus-loss = yes
width           = 40
lines           = 12
tabs            = 4
horizontal-pad  = 16
vertical-pad    = 8
inner-pad       = 8

[colors]
# background / text / match / selection / border
background      = 002b36f2
text            = 839496ff
match           = 268bd2ff
selection       = 073642ff
selection-text  = fdf6e3ff
selection-match = 2aa198ff
border          = 268bd280

[border]
width           = 2
radius          = 8

[dmenu]
# For cliphist pipe
exit-immediately-if-empty = yes
